name: Deploy to EC2 via internal Docker build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload source code to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "~/bugzero-deploy"

    - name: SSH into EC2 and build & run Docker
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/bugzero-deploy
          chmod +x gradlew
          ./gradlew clean build
          docker stop cointalk || true
          docker rm cointalk || true
          docker build -t cointalk .
          docker run -d --network host --name cointalk cointalk
