name: Deploy to EC2 via Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - run: chmod +x gradlew

    - run: ./gradlew clean build

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: docker build -t ghcr.io/ureca-bug-zero/bugzero-backend:latest .

    - run: docker push ghcr.io/ureca-bug-zero/bugzero-backend:latest

    - uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }} 
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/ureca-bug-zero/bugzero-backend:latest
          docker stop cointalk || true
          docker rm cointalk || true
          docker run -d --name cointalk -p 80:8080 ghcr.io/ureca-bug-zero/bugzero-backend:latest
